#include "errors.h"
#include <QDebug>

enum ErrorList {
    FT_INVALID_HANDLE = 1,
    FT_DEVICE_NOT_FOUND,
    FT_DEVICE_NOT_OPENED_OVERRYDE_RMMOD,
    FT_IO_ERROR,
    FT_INSUFFICIENT_RESOURCES,
    FT_INVALID_PARAMETER,
    FT_INVALID_BAUD_RATE,
    FT_DEVICE_NOT_OPENED_FOR_ERASE,
    FT_DEVICE_NOT_OPENED_FOR_WRITE,
    FT_FAILED_TO_WRITE_DEVICE,
    FT_EEPROM_READ_FAILED,
    FT_EEPROM_WRITE_FAILED,
    FT_EEPROM_ERASE_FAILED,
    FT_EEPROM_NOT_PRESENT,
    FT_EEPROM_NOT_PROGRAMMED,
    FT_INVALID_ARGS,
    FT_NOT_SUPPORTED,
    FT_OTHER_ERROR,
    FT_DEVICE_LIST_NOT_READY,
    ER_401_CHIP_INFO_READ_FAIL = 401,
    ER_402_CHIP_DATA_MEMORY_ALLOCATION_ERROR,
    ER_403_CHIP_DATA_READ_ERROR,
    ER_404_ADC_NOT_FOUND_BY_NAME,
    ER_405_CHIP_RESET_FAIL,
    ER_406_PORT_BAUDRATE_SET_FAIL,
    ER_407_PORT_PARAMETERS_SET_FAIL,
    ER_408_PORT_DTR_SET_FAIL,
    ER_409_PORT_FLOW_CONTROL_SET_FAIL,
    ER_410_PORT_RTS_SET_FAIL

    /*
    {401, "Не удалось получить информацию о чипе FT"},
    {402, "Не удалось выделить память под данные с чипа FT"},
    {403, "Не удалось прочитать данные с чипа FT"},
    {404, "Устройстово присутствует, но не удалось распознать АЦП по имени"},
    {405, "Не удалось ресетнуть чип FT. Чип завис при инициализации?"},
    {406, "Не удалось установить скорость обмена с портом (baudrate)"},
    {407, "Не удалось установить параметры порта (8-1-N)"},
    {408, "Не удалось установить DTR"},
    {409, "Не удалось установить Flow Control"},
    {410, "Не удалось установить RTS"},
    {304, "Устройство не закрылось (FT_Close)"},
    {305, "Не удалось остановить АЦП (ADC_STOP)"},
    {306, "Не удалось запустить АЦП (ADC_START)"},
    {307, "Не удалось отправить команду на очистку памяти (ADC_WRITE)"},
    {308, "Не удалось очистить память (cls)"},
    {309, "Память очистилась не полностью (BytesWritten != mem_size)"},
    {310, "Не удалось отправить команду на запись памяти (ADC_WRITE)"},
    {311, "Не удалось записать память (wrt)"},
    {312, "Память записалась не полностью (BytesWritten != mem_size)"},
    {313, "Не удалось отправить команду на чтение памяти АЦП (ADC_READ)"},
    {314, "Не удалось прочитать всю память АЦП (Read Timeout)"},
    {315, "Не удалось прочитать память АЦП (buf)"},
    {316, "Не удалось отправить команду на сброс логики (ADC_RESET)"},
    {317, "Не удалось отправить команду на сброс порога (ADC_SEL_CH)"},
    {317, "Не удалось отправить команду на сброс порога (ADC_MINUS)"},
    {319, "Не удалось отправить команду на сброс порога ГРУБО (ADC_GRUBO)"},
    {320, "Не удалось отправить команду на сброс порога (ADC_SEL_CH)"},
    {321, "Не удалось отправить команду на сброс порога (ADC_MINUS)"},
    {322, "Не удалось отправить команду на сброс порога ТОЧНО (ADC_TOCHN)"},
    {323, "Не удалось отправить команду на установку порога (ADC_SEL_CH)"},
    {324, "Не удалось отправить команду на установку порога (ADC_PLUS)"},
    {325, "Не удалось отправить команду на установку порога ГРУБО (ADC_GRUBO)"},
    {326, "Не удалось отправить команду на установку порога (ADC_SEL_CH)"},
    {327, "Не удалось отправить команду на установку порога (ADC_PLUS)"},
    {328, "Не удалось отправить команду на установку порога ТОЧНО (ADC_TOCHN)"},
    {501, "Нет файла настроек, используем настройки по умолчанию"},
    {502, "Файл настроек прочитался с ошибками, файл пересоздан"}*/
};

void get_error(uint errCode)
{
    qDebug() << ErrorList(errCode);
}
